project:
  type: website
  output-dir: docs

website:
  title: "qgtools"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: examples/index.qmd
        text: Examples
      - href: https://github.com/psoerensen/qgtools
        text: GitHub

format:
  html:
    embed-resources: true
    theme: flatly
    toc: true
    code-fold: false
    highlight-style: github
